recharge.iced obtains the transaction fee estimate from an api
keybase/blockchain-tools pull request #1
Opened 2017-05-17 21:35 UTC by modalduality

2017-05-18 13:14 UTC, maxtaco commented on src/recharge.iced
> +  fee_estimator : (opts, cb) ->
How about?

```iced
fee_estimator : ({type, feePerByteLimit, tx}, cb) ->
```

2017-05-18 13:18 UTC, maxtaco requested changes
Just as a sanity check, how many times is the transaction fee estimate called for making an N-sized recharge?  I would expect (N+1), in which case it might make sense to only make ~2 API calls to 21.co.  I'm worried we'll run up against their rate limit otherwise.

2017-05-18 13:18 UTC, maxtaco commented on src/recharge.iced
> +    btc_opts = {
Should somehow read this out of the config file in the production (non-test) case.

2017-05-18 14:40 UTC, modalduality commented
Now the fee estimation is done when initializing base and the @marginal_fee is stored as a class variable for use by any subclass without calling the API multiple times per run of the script.

2017-05-19 19:11 UTC, maxtaco approved these changes

2017-05-19 19:14 UTC, maxtaco requested changes
One small change

2017-05-19 19:14 UTC, maxtaco commented on src/base.iced
> +        fees = JSON.parse(body)['fees']
actually can you make this a little more robust?  `JSON.parse` can throw, and `fees` might be undefined. In either case the program will crash.

2017-05-19 20:08 UTC, modalduality commented
Some different ways this could be handled,
-Use a schema library
-Move aget/aassert to a util library in this package
-Move aget/aassert to iced-utils

2017-05-19 20:13 UTC, maxtaco commented on src/base.iced
> +        await @aget body_json, 'fees', esc defer fees
well i've never seen this done before, but it works.  i guess if i were doing this i would probably write:

```iced
currentClearanceMins = 10000
for {maxMinutes,MaxFee} in (body_json.fees or []) when maxMinutes <= currentClearanceMins
  currentClearanceMins = maxMinutes
  currentFee = maxFee
  
```

2017-05-19 20:33 UTC, maxtaco approved these changes

2017-05-19 20:33 UTC, merged